import localforage from 'localforage';

export async function saveLogo(base64: string) {
  await localforage.setItem('storeLogo', base64);
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new Event('store_logo_updated'));
  }
}

export async function getLogo(): Promise<string | null> {
  return await localforage.getItem('storeLogo');
}

import { 
  User, Product, InventoryMovement, RepairOrder, Order, 
  MembershipTier, ChatConversation, Employee, Payroll, 
  AuditLog, ClientProfile, LogisticsDelivery, MarketingCampaign,
  AppSettings, Banner, HistoricalSku
} from '../types';

// The pre-defined admin password generated by the system (exactly 12 characters, alphanumeric)
export const ADMIN_PASSWORD = "T7vX9zR2mK4w";

interface Database {
  users: User[];
  products: Product[];
  inventory_movements: InventoryMovement[];
  repair_orders: RepairOrder[];
  orders: Order[];
  membership_tiers: MembershipTier[];
  chat_conversations: ChatConversation[];
  employees: Employee[];
  payroll: Payroll[];
  audit_log: AuditLog[];
  clients: ClientProfile[];
  deliveries: LogisticsDelivery[];
  marketing_campaigns: MarketingCampaign[];
  banners: Banner[];
  settings?: AppSettings;
  historical_skus?: HistoricalSku[];
}

const DEFAULT_BANNERS: Banner[] = [
  {
    id: 'BAN-001',
    title: 'Reparación desde Casa',
    description: 'Ahorre tiempo: recogemos su equipo en la GAM mediante mensajero o puede retirarlo con cita previa en nuestro domicilio fiscal.',
    type: 'Servicios',
    active: true
  },
  {
    id: 'BAN-002',
    title: 'Repuestos Originales GAM',
    description: 'Consiga sus pantallas y repuestos hoy mismo con entrega express GAM motorizada o retire gratis en Sabana Norte.',
    type: 'Repuestos',
    active: true
  },
  {
    id: 'BAN-003',
    title: 'Soporte Virtual Remoto',
    description: 'Asistencia inmediata por chat web y videollamada para diagnósticos rápidos de software y configuraciones.',
    type: 'Soporte',
    active: true
  }
];

const DEFAULT_MEMBERSHIPS: MembershipTier[] = [
  {
    id: 'Plata',
    name: 'Membresía Plata',
    price: 5000,
    discountPercent: 5,
    shippingSJ: 2000,
    shippingOther: 3500,
    active: true,
    features: ['Soporte estándar', 'Garantía extendida (+1 mes)', 'Descuento del 5%']
  },
  {
    id: 'Oro',
    name: 'Membresía Oro',
    price: 10000,
    discountPercent: 10,
    shippingSJ: 0, // Envío gratis a San José
    shippingOther: 2000,
    active: true,
    features: ['Soporte prioritario', 'Garantía extendida (+3 meses)', 'Descuento del 10%', 'Envío Gratis a San José']
  },
  {
    id: 'Platino',
    name: 'Membresía Platino',
    price: 20000,
    discountPercent: 15,
    shippingSJ: 0,
    shippingOther: 0, // Envío gratis a todo el país
    active: true,
    features: ['Soporte VIP 24/7', 'Garantía extendida (+9 meses)', 'Descuento del 15%', 'Envío Gratis Nacional', 'Mantenimiento preventivo anual']
  }
];

const DEFAULT_SETTINGS: AppSettings = {
  cedulaJuridica: '3-101-987452',
  companyPhone: '+506 6421 4795',
  companyAddress: 'San José, Barrio Escalante, de la Iglesia de Santa Teresita 100m norte, casa color blanca #45B (Taller y Bodega en Casa)',
  workshopAddress: 'San José, Barrio Escalante, de la Iglesia de Santa Teresita 100m norte, casa color blanca #45B (Estudio de Reparaciones)',
  pickupHours: 'Lunes a Viernes de 1:00 PM a 6:00 PM, Sábados de 9:00 AM a 1:00 PM',
  maxStockLimit: 50
};

export function getDB(): Database {
  const data = localStorage.getItem('technoverse_db');
  if (data) {
    try {
      const db = JSON.parse(data) as Database;
      if (!db.settings) {
        db.settings = DEFAULT_SETTINGS;
        saveDB(db);
      }
      return db;
    } catch (e) {
      console.error('Error parsing database', e);
    }
  }

  // Initialize fresh, completely empty database as requested (except pre-defined admin & tiers)
  const freshDB: Database = {
    users: [
      {
        id: 'admin-id',
        email: 'admin@technoverse.com',
        role: 'Dueño',
        name: 'Administrador Technoverse'
      }
    ],
    products: [],
    inventory_movements: [],
    repair_orders: [],
    orders: [],
    membership_tiers: DEFAULT_MEMBERSHIPS,
    chat_conversations: [],
    employees: [],
    payroll: [],
    audit_log: [
      {
        id: 'init-log',
        userEmail: 'sistema@technoverse.com',
        module: 'Seguridad',
        action: 'Inicialización',
        detail: 'Base de datos Technoverse iniciada. Sistema limpio sin registros precargados de demostración con ajustes adaptados para negocio desde casa.',
        timestamp: new Date().toISOString()
      }
    ],
    clients: [],
    deliveries: [],
    marketing_campaigns: [],
    banners: DEFAULT_BANNERS,
    settings: DEFAULT_SETTINGS
  };

  saveDB(freshDB);
  return freshDB;
}

export function saveDB(db: Database) {
  if (db.products) {
    if (!db.historical_skus) {
      db.historical_skus = [];
    }

    const activeProducts: Product[] = [];

    db.products.forEach(p => {
      if (p.sku) {
        const skuData = {
          sku: p.sku,
          name: p.name,
          category: p.category,
          price: p.price,
          cost: p.cost,
          imageUrl: p.imageUrl
        };
        const existingIdx = db.historical_skus!.findIndex(h => h && h.sku && typeof h.sku === 'string' && h.sku.toLowerCase() === p.sku.toLowerCase().trim());
        if (p.stock <= 0 || p.active === false) {
          p.active = false;
          p.stock = 0;
          if (existingIdx === -1) {
            db.historical_skus!.push(skuData);
          } else {
            db.historical_skus![existingIdx] = skuData;
          }
          if (typeof window !== 'undefined') {
            try {
              window.dispatchEvent(new CustomEvent('product:deleted', { detail: p }));
            } catch (e) {}
          }
        } else {
          // If the product is active, remove it from historical_skus list
          db.historical_skus = db.historical_skus!.filter(h => h && h.sku && typeof h.sku === 'string' && h.sku.toLowerCase().trim() !== p.sku.toLowerCase().trim());
          activeProducts.push(p);
        }
      } else {
        if (p.active !== false && p.stock > 0) {
          activeProducts.push(p);
        }
      }
    });

    db.products = activeProducts;
  }

  localStorage.setItem('technoverse_db', JSON.stringify(db));

  // Dispatch standard and custom events to notify other components/views in real-time
  if (typeof window !== 'undefined') {
    try {
      const storageEvent = new StorageEvent('storage', {
        key: 'technoverse_db',
        newValue: JSON.stringify(db),
      });
      window.dispatchEvent(storageEvent);
    } catch (e) {
      // Ignored if StorageEvent construction/dispatch is restricted
    }

    try {
      window.dispatchEvent(new CustomEvent('technoverse_db_updated', { detail: db }));
    } catch (e) {
      // Ignored if CustomEvent is restricted
    }

    // Send instant update message to all open tabs/iframes
    try {
      const channel = new BroadcastChannel('technoverse_db_channel');
      channel.postMessage({ type: 'UPDATE_DB', db });
      channel.close();
    } catch (err) {
      // BroadcastChannel might not be available or fail in extremely restricted sandboxes
    }
  }
}

// Log an event in the Audit Log
export function addAuditLog(userEmail: string, module: string, action: string, detail: string, existingDb?: Database) {
  const db = existingDb || getDB();
  const newLog: AuditLog = {
    id: `LOG-${Math.floor(100000 + Math.random() * 900000)}`,
    userEmail: userEmail || 'admin@technoverse.com',
    module,
    action,
    detail,
    timestamp: new Date().toISOString()
  };
  if (!db.audit_log) {
    db.audit_log = [];
  }
  db.audit_log.unshift(newLog);
  if (!existingDb) {
    saveDB(db);
  }
}
